# Generated by Django 6.1.1 on 2026-09-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(help_text="Унікальний ідентифікатор для URL, напр. 'fantasy'", max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
